# Generated by Django 2.2.2 on 2019-06-27 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('order', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=1024)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Контрольный пункт',
                'verbose_name_plural': 'Контрольные пункты',
                'db_table': 'control_point',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CPProtocol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('control_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='race.ControlPoint')),
            ],
            options={
                'verbose_name': 'Протокол Контрольного пункта',
                'verbose_name_plural': 'Протоколы Контрольных пунктов',
                'db_table': 'c_p_protocol',
                'ordering': ['-date'],
            },
        ),
    ]
