# Generated by Django 2.2.2 on 2019-06-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlpoint',
            name='order',
            field=models.IntegerField(unique=True),
        ),
    ]
