# Generated by Django 2.2.2 on 2019-06-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0004_auto_20190628_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpprotocol',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
