# Generated by Django 2.2.2 on 2019-06-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0005_auto_20190628_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultRuns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField()),
                ('date_update', models.DateTimeField()),
            ],
        ),
    ]
