# Generated by Django 2.2.2 on 2019-06-29 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0006_resultruns'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultruns',
            old_name='info',
            new_name='passed_checkpoint',
        ),
        migrations.AddField(
            model_name='resultruns',
            name='pre_result',
            field=models.TextField(default='dawda'),
            preserve_default=False,
        ),
    ]
