# Generated by Django 2.2.2 on 2019-06-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0007_auto_20190629_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunGuys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
    ]
